% num_angles = 360 ; % 6 fps
num_angles = 180 ; % 3 fps
% num_angles = 60 ; % 1 fps

% angles = [ 90, 45 ] + [ linspace( 0, 360 * ( 1 - 1 / num_angles ), ...
% angles = [ 90, 30 ] + [ linspace( 0, 360 * ( 1 - 1 / num_angles ), ...
angles = [ 90, 15 ] + [ linspace( 0, 360 * ( 1 - 1 / num_angles ), ...
                                                     num_angles )', ...
                                              zeros( num_angles, 1 )];  % 360 rotation at 45 degrees elevation, starting at 90 degrees azimuthal

animate_strands_3D( gcf, [ 'animation_vessels_', num2str( num_angles ), '.gif' ], angles )