%% Linninger vectorization
% 8/4/2021 SAM

%% Input stacks:
OutputDirectory = 'E:\Linninger\' ; input_names{ 1 } = 'Subj58\Z2967_to_Z3104.tif' ; 

microns_per_voxel = [ ];
% microns_per_voxel( 1, 1 : 3 ) = [0.39, 0.39, 0.6]; !!!! Z dimension too long !!! % [ y, x, z ] == !!!!milimeters!!!!!!!_per_voxel - SAM 6/16/21
microns_per_voxel( 1, 1 : 3 ) = [0.39, 0.39, 0.39]; % [ y, x, z ] == !!!!milimeters!!!!!!!_per_voxel - SAM 6/16/21

number_of_stacks = length( input_names );

stackID_range = 1 : number_of_stacks ;        

%% Workflow:

start_workflow = 'energy' ;
% start_workflow = 'vertices' ;
% start_workflow = 'edges' ;
% start_workflow = 'network' ;
% start_workflow = 'none' ;

% Settings:

scales_per_octave = 1 ; % 3 per radius octave

for stackID = stackID_range
    
    switch start_workflow
    
        case 'energy'
    
            name_value_pair_inputs = {  'OutputDirectory',                   OutputDirectory, ...
                                        'PreviousBatch',                    'none',               ...
                                        'PreviousWorkflow',                 'none',            ...
                                        'StartWorkflow',                    'energy',                           ...
                                        'FinalWorkflow',                    'network',                              ...
                            ...            'FinalWorkflow',                    'energy',                              ...                    
                                        'Visual',                           'productive',                       ...
                                        'SpecialOutput', { 'histograms', 'vmv', 'depth', 'strands', 'directions' },        ...                                        
                                        'NewBatch',                         'yes',                    ...
                                        'Presumptive',                       true,                              ...
                                        'matching_kernel_string',            '3D gaussian conv annular pulse',            ... % !!!! depricated parameter !!!! built-in parmater to energy_filter, A = 6 !!!!! make this a recorded input
                 ...                       'symmetry_ratio_factor',                    1.5,         ... !!! depricated parameter.  
...                                        'gaussian_to_ideal_ratio',               0.6,         ...
   ...                                  'spherical_to_annular_ratio',               0.8, ...
                                        'gaussian_to_ideal_ratio',               ( 1 - 2 ^ - ( 2 / scales_per_octave / 3 )) .^ 0.5 ,         ... % pythagorean half (root(2)/2) of the radius is due to blurring when the radius is sampled at every doubling
                                     'spherical_to_annular_ratio',               1, ...
   ...                                        'microns_per_voxel',                        [0.78, 0.78, 5],          ... 
                                        'microns_per_voxel',                        microns_per_voxel( stackID, : ),          ... 
                                       'radius_of_smallest_vessel_in_microns',      microns_per_voxel( stackID, 1 ),                         ...
...                                       'radius_of_smallest_vessel_in_microns',      microns_per_voxel( stackID, 1 )*1.5,                         ...
                                        'radius_of_largest_vessel_in_microns',      microns_per_voxel( stackID, 1 )*7,                         ...
                                        'approximating_PSF',                        false,                       ...
                                        'scales_per_octave',                        scales_per_octave,                        ... 
                                        'max_voxels_per_node_energy',               1e6,                    ...
                                        'vessel_wall_thickness_in_microns',         0                           };

            time_stamp = vectorize_V200([ OutputDirectory, input_names{ stackID }], name_value_pair_inputs{ 1, : }); 

        
        otherwise

            name_value_pair_inputs = {  'OutputDirectory',                   OutputDirectory,  ...
                                        'PreviousBatch',                    'prompt',   ...
                                        'PreviousWorkflow',                 'recent',          ...
                                        'StartWorkflow',                    start_workflow,    ...
                                   ...     'FinalWorkflow',                    'network',         ...
    ...                                    'Visual',                           'productive',      ...
                     ...                   'Visual',                           'vertices',      ...
                                        'NewBatch',                         'no',              ...
                                        'Presumptive',                       true,             ...
                          ...              'VertexCuration',                   'manual',          ...
                            ...            'VertexCuration',                   'none',          ...
                           ...             'VertexCuration',                   'mutual edges',          ...
                           ...          'VertexCuration',                   'auto',          ...
                                        'space_strel_apothem_edges',        int64(1),           ...
                                        'number_of_edges_per_vertex',       2,               ... 
                            ...            'number_of_edges_per_vertex',       4,               ...
                                        'sigma_edge_smoothing',             0.5,               ...
                           ...            'EdgeCuration',                     'manual', ...
                           ...             'EdgeCuration',                     'none', ...
    ...                                    'SpecialOutput', { 'depth', 'strands', 'directions', 'upsampled', '3D-strands' }};
    ...                                    'SpecialOutput', { '3D-strands' }};
...                                        'SpecialOutput', { 'depth-stats' }};
    ...                                    'SpecialOutput', { 'upsampled' }};    
    ...                                     'SpecialOutput', { 'depth', 'directions' }};
      ...                                  'SpecialOutput', { 'histograms', 'vmv', 'depth', 'strands', 'directions' }};    
...                                         'SpecialOutput', 'casx' }
...                                            'SpecialOutput', {'histograms', 'vmv', '3D-z-directions', '3D-radii', '3D-strands', 'directions', 'strands' }};
                                            'SpecialOutput', {'vmv', '3D-z-directions', '3D-radii', '3D-strands', 'directions', 'strands' }};
            time_stamp = vectorize_V200( name_value_pair_inputs{ 1, : }); 
    end            
end
