%% Dafna vectorization
% 3/11/2021 SAM

%% Input stack:
input_names{ 1 } = '(3)207 20x FITC_2_Motion_Corrected.tif' ; OutputDirectory = 'E:\Dafna\207wt\' ; % SAM 6/26/21

microns_per_voxel = [ ];
% microns_per_voxel( 1, 1 : 3 ) = [2, 2, 5]; % [ y, x, z ] == microns_per_voxel % SAM 3/22/22
microns_per_voxel( 1, 1 : 3 ) = [1.186 1.186, 2]; % SAM 3/22/22

number_of_stacks = length( input_names );

stackID_range = 1 : number_of_stacks ;        

%% Workflow:

start_workflow = 'energy' ;
% start_workflow = 'vertices' ;
% start_workflow = 'edges' ;
% start_workflow = 'network' ;
% start_workflow = 'none' ;

% Settings:

% PSF_fudge_factor = 2 ;
PSF_fudge_factor = 1 ;

for stackID = stackID_range
    
    switch start_workflow
    
        case 'energy'
    
            name_value_pair_inputs = {  'OutputDirectory',                   OutputDirectory, ...
                                        'PreviousBatch',                    'none',               ...
                                        'PreviousWorkflow',                 'none',            ...
                                        'StartWorkflow',                    'energy',                           ...
                                       'FinalWorkflow',                    'network',                              ...
                                   ...     'FinalWorkflow',                    'energy',                              ...                    
                                        'Visual',                           'productive',                       ...
                                        'SpecialOutput', { 'histograms', 'vmv', 'depth', 'strands', 'directions' },        ...                                        
                                        'NewBatch',                         'yes',                    ...
                                        'Presumptive',                       true,                              ...
                                        'matching_kernel_string',            '3D gaussian conv annular pulse',            ... % !!!! depricated parameter !!!! built-in parmater to energy_filter, A = 6 !!!!! make this a recorded input
                 ...                       'symmetry_ratio_factor',                    1.5,         ... !!! depricated parameter.  
                                        'gaussian_to_ideal_ratio',               0.6, ... % 0.8 % if noisy
                                     'spherical_to_annular_ratio',               0.8, ... % 0.2 % if vessel wall is good source of contrast
    ...                                    'gaussian_to_ideal_ratio',               0.5,         ...
    ...                                 'spherical_to_annular_ratio',               0.5, ...
...                                        'microns_per_voxel',                        [0.78, 0.78, 5],          ... 
                                        'microns_per_voxel',                        microns_per_voxel( stackID, : ),          ... 
                                       'radius_of_smallest_vessel_in_microns',      1.5,                         ...
                                        'radius_of_largest_vessel_in_microns',      60,                         ...
                                        'approximating_PSF',                        true,                       ...
                                        'excitation_wavelength',                    0.8 * PSF_fudge_factor,     ... % 800 nm laser
                                        'scales_per_octave',                        3,                        ... 
                                        'max_voxels_per_node_energy',               1e6,                    ...
                                        'vessel_wall_thickness_in_microns',         0                           };

            time_stamp = vectorize_V200([ OutputDirectory, input_names{ stackID }], name_value_pair_inputs{ 1, : }); 

        
        otherwise

            name_value_pair_inputs = {  'OutputDirectory',                   OutputDirectory,  ...
                                        ...'PreviousBatch',                    'prompt',   ...
             ...                           'PreviousBatch',                    'recent',   ...
                     ...                   'PreviousBatch',                    '210810-022653', ...
                         ...               'PreviousBatch',                    '220126-010215', ...
                                        'PreviousWorkflow',                 'recent',          ...
                                        'StartWorkflow',                    start_workflow,    ...
                                   ...     'FinalWorkflow',                    'network',         ...
    ...                                    'Visual',                           'productive',      ...
                     ...                   'Visual',                           'vertices',      ...
                                        'NewBatch',                         'no',              ...
                                        'Presumptive',                       true,             ...
                      ...                  'VertexCuration',                   'manual',          ...
                            ...            'VertexCuration',                   'none',          ...
                           ...             'VertexCuration',                   'mutual edges',          ...
                           ...          'VertexCuration',                   'auto',          ...
                                        'space_strel_apothem_edges',        int64(1),           ...
                                        'number_of_edges_per_vertex',       2,               ... 
                            ...            'number_of_edges_per_vertex',       4,               ...
                                        'sigma_edge_smoothing',             0.5,               ...
                            ...            'EdgeCuration',                     'manual', ...
                           ...             'EdgeCuration',                     'none', ...
    ...                                    'SpecialOutput', { 'depth', 'strands', 'directions', 'upsampled', '3D-strands' }};
    ...                                    'SpecialOutput', { '3D-strands' }};
...                                        'SpecialOutput', { 'depth-stats' }};
    ...                                    'SpecialOutput', { 'upsampled' }};    
    ...                                     'SpecialOutput', { 'depth', 'directions' }};
                                        'SpecialOutput', { 'histograms', 'vmv', 'depth', 'strands', 'directions' }};    
    ...                                        'SpecialOutput', 'flow-field' };

            time_stamp = vectorize_V200( name_value_pair_inputs{ 1, : }); 
    end            
end
