%% Chakameh OCT vectorization
% SAM 12/3/2019

input_name = 'Reslice of cdvfile_complex.tif' ;

OutputDirectory = 'E:\Chakameh\' ;

start_workflow = 'energy' ;
% start_workflow = 'vertices' ;
% start_workflow = 'edges' ;
% start_workflow = 'network' ;
% start_workflow = 'none' ;

PSF_fudge_factor = 4 ;

switch start_workflow

    case 'energy'

        name_value_pair_inputs = {  'OutputDirectory',                   OutputDirectory, ...
                                    'PreviousBatch',                    'none',               ...
                                    'PreviousWorkflow',                 'none',            ...
                                    'StartWorkflow',                    'energy',                           ...
                                    'FinalWorkflow',                    'network',                              ...
                        ...            'FinalWorkflow',                    'energy',                              ...                    
                                    'Visual',                           'productive',                       ...
                                    'NewBatch',                         'yes',                    ...
                                    'Presumptive',                       true,                              ...
                                    'matching_kernel_string',            '3D gaussian conv annular pulse',            ... % !!!! depricated parameter !!!! built-in parmater to energy_filter, A = 6 !!!!! make this a recorded input
             ...                       'symmetry_ratio_factor',                    1.5,         ... !!! depricated parameter.  
                                    'gaussian_to_ideal_ratio',                  0.5,         ...
                                    'spherical_to_annular_ratio',               6/7, ...
                                    'microns_per_voxel',                        2 * 1000 / 512 * [ 1, 1, 1 ],          ...
                                    'radius_of_smallest_vessel_in_microns',     6,                          ...
                                    'radius_of_largest_vessel_in_microns',      100,                         ...
                                    'approximating_PSF',                        true,                       ...
                                    'excitation_wavelength',                    1.3 * PSF_fudge_factor,     ...
                                    'scales_per_octave',                        3,                        ... 
                                    'max_voxels_per_node_energy',               1e6,                    ...
                                    'vessel_wall_thickness_in_microns',         0                           };


        time_stamp = vectorize_V200([ OutputDirectory, input_name ], name_value_pair_inputs{ 1, : }); 


    otherwise

        name_value_pair_inputs = {  'OutputDirectory',                   OutputDirectory,  ...
                                    'PreviousBatch',                    'recent',   ...
                                    'PreviousWorkflow',                 'recent',          ...
                                    'StartWorkflow',                    start_workflow,    ...
                               ...     'FinalWorkflow',                    'network',         ...
                                    'Visual',                           'productive',      ...
                                    'NewBatch',                         'no',              ...
                                    'Presumptive',                       true,             ...
                             ...       'VertexCuration',                   'manual',          ...
                                    'VertexCuration',                   'none',          ...
                                    'length_dilation_ratio_vertices',   2,               ... new default
                                    'number_of_edges_per_vertex',       2,               ... new default 11/6/19
                        ...            'number_of_edges_per_vertex',       4,               ...
                                    'sigma_edge_smoothing',             0.5,               ...
                        ...            'EdgeCuration',                     'manual'           };
                                    'EdgeCuration',                     'none', ...
...                                    'SpecialOutput', { 'depth', 'strands', 'directions', 'upsampled', '3D-strands' }};
                                    'SpecialOutput', { '3D-strands' }};
...                                    'SpecialOutput', { 'depth-stats' }};
...                                     'SpecialOutput', { 'depth', 'directions' }};

        time_stamp = vectorize_V200( name_value_pair_inputs{ 1, : }); 
end            

