%% Michael's annular signal images
% SAM 8/14/2019

% signal_shape = 'annular' ;
signal_shape = 'spherical' ;

OutputDirectory = 'E:\Michael\' ;

PSF_fudge_factor = 1 ;

% start_workflow = 'energy' ;
% start_workflow = 'vertices' ;
% start_workflow = 'edges' ;
% start_workflow = 'network' ;
start_workflow = 'none' ;

switch start_workflow
    
    case 'energy'
                                
        switch signal_shape

            case 'annular'
                
                input_image_name = 'tie2gfp16 9juyly2018 870nm region a-082-1.tif' ;
                
                gaussian_to_ideal_ratio    = 0.5 ;
                spherical_to_annular_ratio = 0.5 ;
                
            case 'spherical'
                
                input_image_name = 'tie2gfp16 9juyly2018 870nm region a-082_Cycle00001_Ch3_00000.tif' ;
                
                gaussian_to_ideal_ratio    = 0.75 ;
                spherical_to_annular_ratio = 0.5 ;
                
        end
        
        name_value_pair_inputs = {  'OutputDirectory',                   OutputDirectory,                ...
                                    'PreviousBatch',                    'none',                          ...
                                    'PreviousWorkflow',                 'none',                          ...
                                    'StartWorkflow',                    'energy',                        ...
                                    'FinalWorkflow',                    'network',                       ...
                                    'Visual',                           'productive',                    ...
                                    'NewBatch',                         'yes',                           ...
                                    'Presumptive',                       true,                           ...
          ...                          'matching_kernel_string',            '3D gaussian conv annular pulse', ... 
                                    'gaussian_to_ideal_ratio',                  gaussian_to_ideal_ratio,                     ... 
          ...                          'symmetry_ratio_factor',                    0.1,                    ... !!!! depricated parameter   
           ...                         'symmetry_ratio_factor',                    1/4,                    ...
                                    'spherical_to_annular_ratio',               spherical_to_annular_ratio,                     ...
                                    'microns_per_voxel',                        0.916*[1, 1, 2.18],      ...
                                    'radius_of_smallest_vessel_in_microns',     1.5,                     ...
                                    'radius_of_largest_vessel_in_microns',      60,                      ...
                                    'approximating_PSF',                        true,                    ...
                                    'excitation_wavelength',                    0.95 * PSF_fudge_factor, ...
                                    'scales_per_octave',                        6,                       ... 
                                    'max_voxels_per_node_energy',               1e6,                     ...
                                    'vessel_wall_thickness_in_microns',         0                        };        
                
        time_stamp = vectorize_V200([ OutputDirectory, input_image_name ], name_value_pair_inputs{ 1, : }); 
                
    otherwise
        
        name_value_pair_inputs = {  'OutputDirectory',                   OutputDirectory,  ...
    ...                                'PreviousBatch',                    'recent',   ...
                                    'PreviousBatch',                    '190912-113508',   ...    
                                    'PreviousWorkflow',                 'recent',          ...
                                    'StartWorkflow',                    start_workflow,    ...
                               ...     'FinalWorkflow',                    'network',         ...
                                    'Visual',                           'productive',      ...
                                    'NewBatch',                         'no',              ...
                                    'Presumptive',                       true,             ...
                                    'VertexCuration',                   'none',          ...
                             ...       'EdgeCuration',                     'manual'           };
                                    'EdgeCuration',                     'none', ...
...                                    'SpecialOutput', { 'depth', 'strands', 'directions', 'upsampled', '3D-strands' }};
...                                    'SpecialOutput', { '3D-strands' }};
...                                    'SpecialOutput', { 'depth-stats' }};
                                     'SpecialOutput', { 'depth', 'directions' }};
                                
        time_stamp = vectorize_V200( name_value_pair_inputs{ 1, : }); 
        
end
        
        



